# Build Stage
FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o main .

# Run Stage (use a minimal image)
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .

# Optional: Set environment variables at runtime
# ENV PORT=8080

# Expose if needed
# EXPOSE 8080

ENTRYPOINT ["./main"]
